ref(ResetArch,RiceArch): installing fonts with pacman

diff --git a/.local/bin/RiceArch b/.local/bin/RiceArch
--- a/.local/bin/RiceArch
+++ b/.local/bin/RiceArch
@@ -88,7 +88,7 @@
 # mount -o noatime,compress=lzo,subvol=@snapshots  /dev/vda3 /mnt/.snapshots
 # mount                                            /dev/vda2 /mnt/boot/efi
 # pacstrap /mnt base base-devel broadcom-wl btrfs-progs efibootmgr git grub linux linux-firmware networkmanager snapper
-# genfstab U /mnt >> /mnt/etc/fstab
+# genfstab -U /mnt >> /mnt/etc/fstab
 
 #------------------------------------ After-Chroot (zram + grub) -------------------------------------#
 
@@ -105,57 +105,49 @@
 #========================================== rollback layout ==========================================#
 
 # ● home 》
-# ○ snapper-rollback to "base-install"
+# ○ snapper-rollback to "appman code google-chrome"
 # ○ snapper delete old snapshots
+# ○ git pull
 # ○ ./ResetArch
-# ○ snapper -c home create -d "after-ResetArch(commit 320)"
 # ○ ./RiceArch
-# ○ check google-chrome
-# ○ check vscode
-# ○ check yay -Scc
+# ○ check vscode.appimage
+# ○ check google-chrome.appimage
 # ○ check neovim plugins
 # ○ check systemctl .services
-# ○ snapper -c home create -d "after-RiceArch(commit 320)"
-# ○ ./Rice
-# ○ snapper -c home create -d "after-Rice(commit 118)"
-# ○ ./larbs.sh
-# ○ snapper -c home create -d "after-larbs(commit ???)"
+# ○ check audio
+# ○ check light (requires video-group and reboot)
+# ○ snapper -c home create -d "after RiceArch(commit 358) sixelrice(commit 131)"
 
 # ● root 》
-# ○ snapper-rollback to "base-install"
+# ○ snapper-rollback to "base base-devel broadcom-wl btrfs-progs efibootmgr grub linux linux-firmware networkmanager snapper synaptics zram-generator"
 # ○ snapper delete old snapshots
-# ○ delete btrfs snapshots created by snapper-rollback
-# ○ ./ResetArch
-# ○ snapper create -d "after-ResetArch(commit 320)"
-# ○ ./RiceArch
+# ○ check broadcom-wl
 # ○ check dataos
+# ○ check pacman parallel downloads
 # ○ check sudoers
-# ○ check snapper-rollback.conf
-# ○ check touchpad
+# ○ check synaptics touchpad
 # ○ check zram
-# ○ snapper create -d "after-RiceArch(commit 320)"
-# ○ ./Rice
+# ○ git clone https://gitlab.com/yucrayeff36/sixelrice ~/.config/nvim
 # ○ check neovim plugins
-# ○ snapper create -d "after-Rice(commit 118)"
-# ○ ./larbs.sh
-# ○ snappet create -d "after-Larbs(commit???)"
+# ○ check yazi
+# ○ snapper -c home create -d "after RiceArch(commit 358) sixelrice(commit 131)"
 
 #=========================================== After-Reboot ============================================#
 
-# ARCH_USER=drknss BTRFS_SNAPSHOT=true RESETARCH_SNAPSHOT=true RICEARCH_SNAPSHOT=true ./RiceArch
+# ARCH_USER=drknss BTRFS_SNAPSHOT=true RICEARCH_SNAPSHOT=true ./RiceArch
 
 # exit on error
 set -eu
 
 # Detect non-root user:
-[ "$(id -u)" != 0 ] && printf "\e[1;31m Run it as root user, ARCH_USER will be added \e[0m\n" && exit 1
+[ "$(id -u)" != 0 ] && printf "\e[1;31m Run it as root user, ARCH_USER will be added if there is no ARCH_USER \e[0m\n" && exit 1
 
 #------------------------------------------ Btrfs snapshot -------------------------------------------#
 
 [ "${BTRFS_SNAPSHOT:-}" == true ] && {
   printf "\n\e[1;33m Btrfs snapshot (@ @home subvolumes required) \e[0m\n"
 
-  pacman -S --noconfirm snapper
+  pacman -S --needed --noconfirm btrfs-progs snapper
   umount /.snapshots
   rm -rf /.snapshots
   snapper --config root create-config /
@@ -170,42 +162,28 @@ set -eu
 
 }
 
-#---------------------------------------- ResetArch snapshot -----------------------------------------#
-
-[ "${RESETARCH_SNAPSHOT:-}" == true ] && {
-  printf "\n\e[1;33m ReseArch snapshot \e[0m\n"
-  ./ResetArch
-  snapper -c root create -d "after-ResetArch"
-  snapper -c home create -d "after-ResetArch"
-}
-
 #----------------------------------------- AddUser + locales -----------------------------------------#
 
 echo "$(tput -T ansi setaf 3) AddUser + locales $(tput -T ansi sgr0)"
 
 USER=${ARCH_USER:-drknss}
 
-# Add user:
 install_user() {
-  [ ! -e "/home/$USER" ] && useradd --shell /bin/zsh -mG audio,video,wheel,tty $USER
-  sudo usermod --append --groups audio,video $USER
+  [ ! -e "/home/$USER" ] && useradd --shell /bin/zsh --move-home --groups audio,video,wheel,tty $USER
+  chsh --shell $(which zsh) $USER
+  usermod --append --groups audio,video $USER
   echo root:toor  | chpasswd
   echo $USER:toor | chpasswd
   echo "%wheel ALL=(ALL:ALL) NOPASSWD: ALL"  > /etc/sudoers.d/wheel
 }
 
 install_locales(){
-  # Locales:
-  # timedatectl set-ntp true
-  # hwclock --systohc
+  # timedatectl set-ntp true && hwclock --systohc
   ln -sf /usr/share/zoneinfo/US/Eastern /etc/localtime
   sed -i 's/#en_US.UTF-8/en_US.UTF-8/' /etc/locale.gen
   locale-gen
-  # echo "LANG=en_US.UTF-8"                    > /etc/locale.conf
-  echo "4rch"                                > /etc/hostname
-  echo "127.0.0.1 localhost"                >> /etc/hosts
-  # echo "::1       localhost"                >> /etc/hosts
-  # echo "127.0.1.1 4rch.localdomain 4rch"    >> /etc/hosts
+  echo "4rch"                                 > /etc/hostname
+  echo "127.0.0.1 localhost"                  >> /etc/hosts
 }
 
 install_user    || ( echo $(tput -T ansi setaf 1) install_user failed    && exit 1; )
@@ -220,17 +198,9 @@ printf "\n\e[1;33m Login User Configs \e[0m\n"
 sudo -u "$USER" -s -- <<'====' # with '====' or "====" makes USER=drknss, with just ==== makes USER=root
   set -eu
 
-  install_dependencies(){
-    [ -e /.dockerenv ] && yes | yay -S --noconfirm tmux
-    yes | yay -S --noconfirm cht.sh-git zsh-fast-syntax-highlighting
-  }
-
   install_dotfiles() {
 
-    mkdir -p $HOME/.config/dotfiles
-    cp -r ../../../archrice $HOME/.config/dotfiles
-    cd $HOME/.config/dotfiles/archrice
-
+    cd "$(git rev-parse --show-toplevel)"
     mkdir -p "$HOME"/.config
     mkdir -p "$HOME"/.local
     stow --restow --verbose --target="$HOME"/.config .config
@@ -240,93 +210,32 @@ sudo -u "$USER" -s -- <<'====' # with '====' or "====" makes USER=drknss, with j
 
   }
 
-  install_fonts() {
-    mkdir -p "$HOME"/.local/share/fonts
+  install_services (){
 
-    # Nerd-Fonts:
-    git clone --depth=1 --filter=blob:none --sparse https://github.com/ryanoasis/nerd-fonts /tmp/nerd-fonts
-    cd /tmp/nerd-fonts
-    git sparse-checkout add patched-fonts/3270
-    git sparse-checkout add patched-fonts/CascadiaCode
-    git sparse-checkout add patched-fonts/FiraCode
-    git sparse-checkout add patched-fonts/Terminus
-    cp -r patched-fonts/3270         "$HOME"/.local/share/fonts
-    cp -r patched-fonts/CascadiaCode "$HOME"/.local/share/fonts
-    cp -r patched-fonts/FiraCode     "$HOME"/.local/share/fonts
-    cp -r patched-fonts/Terminus     "$HOME"/.local/share/fonts
-    cd .. && rm -rf /tmp/nerd-fonts
-
-    # Font-Awesome:
-    git clone --depth=1 --filter=blob:none --sparse https://github.com/FortAwesome/Font-Awesome /tmp/Font-Awesome
-    cd /tmp/Font-Awesome
-    git sparse-checkout add otfs
-    git sparse-checkout add webfonts
-    mkdir           "$HOME"/.local/share/fonts/Font-Awesome
-    cp -r otfs/     "$HOME"/.local/share/fonts/Font-Awesome
-    cp -r webfonts/ "$HOME"/.local/share/fonts/Font-Awesome
-
-    # Noto Sans/Serif/Mono:
-    git clone --depth=1 --filter=blob:none --sparse https://github.com/notofonts/notofonts.github.io /tmp/notofonts.github.io
-    cd /tmp/notofonts.github.io
-    git sparse-checkout add fonts/NotoSans/googlefonts
-    git sparse-checkout add fonts/NotoSansMono/googlefonts
-    git sparse-checkout add fonts/NotoSerif/googlefonts
-    mkdir                                "$HOME"/.local/share/fonts/NotoSans
-    mkdir                                "$HOME"/.local/share/fonts/NotoSansMono
-    mkdir                                "$HOME"/.local/share/fonts/NotoSerif
-    cp -r fonts/NotoSans/googlefonts     "$HOME"/.local/share/fonts/NotoSans
-    cp -r fonts/NotoSansMono/googlefonts "$HOME"/.local/share/fonts/NotoSansMono
-    cp -r fonts/NotoSerif/googlefonts    "$HOME"/.local/share/fonts/NotoSerif
-
-    # Noto CJK:
-    # git clone --depth=1 --filter=blob:none --sparse https://github.com/notofonts/noto-cjk /tmp/noto-cjk
-    # cd /tmp/noto-cjk
-    # git sparse-checkout add google-fonts
-    # mkdir              $HOME/.local/share/fonts/NotoCJK
-    # cp -r google-fonts $HOME/.local/share/fonts/NotoCJK
-
-    # Noto Color-Emoji:
-    git clone --depth=1 --filter=blob:none --sparse https://github.com/googlefonts/noto-emoji /tmp/noto-emoji
-    cd /tmp/noto-emoji
-    git sparse-checkout add fonts
-    mkdir                       "$HOME"/.local/share/fonts/Noto-Emoji
-    cp fonts/NotoColorEmoji.ttf "$HOME"/.local/share/fonts/Noto-Emoji
-
-    # Bedstead Font:
-    curl -L https://bjh21.me.uk/bedstead/bedstead-002.004.zip --output /tmp/bedstead-002.004.zip
-    unzip /tmp/bedstead-002.004.zip -d "$HOME"/.local/share/fonts/
-  }
-
-  install_configs (){
-
-    # sudo systemctl enable NetworkManager
-    # sudo systemctl enable cronie
+    sudo systemctl enable NetworkManager
+    sudo systemctl enable cronie
+    # systemctl --user enable pipewire-pulse
     # systemctl --user enable mpd
-    # systemctl --user enable pipewire
-    # systemctl --user enable touchcursor
     # mpc --port=6601 update
 
-    cp       "$HOME"/.config/wallhaven-2ye15g.jpg  "$HOME"/.local/share/bg
+    cp       "$HOME"/.config/wallpaper-n5glgthngvmb1.jpg  "$HOME"/.local/share/bg
     mkdir -p "$HOME"/.local/share/mpd
-    [ -e /etc/X11/xorg.conf.d ] && sudo mv /etc/X11/xorg.conf.d /etc/X11/xorg.conf.d.synapticsconflicts
-    sudo mkdir -p /etc/X11/xorg.conf.d && sudo cp  "$HOME"/.config/shell/10-synaptics.conf /etc/X11/xorg.conf.d
-    if [ -e /bin/crontab ]; then          crontab  "$HOME"/.local/bin/cron/lowbatnotificationcron; fi
+    [ -e /etc/X11/xorg.conf.d ]        && sudo mv /etc/X11/xorg.conf.d /etc/X11/xorg.conf.d.synapticsconflicts
+    sudo mkdir -p /etc/X11/xorg.conf.d && sudo cp "$HOME"/.config/shell/10-synaptics.conf /etc/X11/xorg.conf.d
+    if [ -e /bin/crontab ]; then          crontab "$HOME"/.local/bin/cron/lowbatnotificationcron; fi
 
   }
 
-  # Main:
-  install_dependencies                          || ( echo "$(tput -T ansi setaf 1) install_dependencies failed"  && exit 1)
-  install_dotfiles                              || ( echo "$(tput -T ansi setaf 1) install_dotfiles failed"      && exit 1)
-  if [ ! -e /.dockerenv ]; then install_fonts   || ( echo "$(tput -T ansi setaf 1) install_nerdfonts failed"     && exit 1); fi
-  if [ ! -e /.dockerenv ]; then install_configs || ( echo "$(tput -T ansi setaf 1) install_configs failed"       && exit 1); fi
+  install_dotfiles || ( echo "$(tput -T ansi setaf 1) install_dotfiles failed" && exit 1)
+  install_services || ( echo "$(tput -T ansi setaf 1) install_services failed" && exit 1)
 ====
 
 #----------------------------------------- RiceArch snapshot -----------------------------------------#
 
-[ "${RICEARCH_SNAPSHOT:-}" == true ] && {
+[ ${RICEARCH_SNAPSHOT:-true} ] && {
   printf "\n\e[1;33m RiceArch snapshot \e[0m\n"
-  snapper -c root create -d "after-RiceArch"
-  snapper -c home create -d "after-RiceArch"
+  snapper -c root create -d "after RiceArch(commit $(git rev-list --count --all))"
+  snapper -c home create -d "after RiceArch(commit $(git rev-list --count --all))"
 }
 
 printf "\e[1;32mDone!\e[0m\n"
